drop table if exists articles;

create table articles (
    id integer not null primary key auto_increment,
    title varchar(128),
    content text
);

insert into articles(title, content) values
  ('The first article', 'Aliquam erat volutpat. Nulla eu dictum nunc. Curabitur mattis leo dui, ac dictum nibh blandit at. Etiam eu orci pretium, pellentesque massa in, finibus ipsum. Aenean finibus, nunc et auctor rutrum, neque elit gravida enim, ac varius sapien quam nec risus. Pellentesque pellentesque, ipsum eu tincidunt aliquet, nisi neque scelerisque diam, eu posuere sapien est vel eros. Aenean euismod interdum metus, posuere vulputate eros rutrum quis. Vivamus convallis vestibulum eros vel dignissim. Etiam dapibus pellentesque lobortis. Sed vel cursus ligula. Nunc id mauris dapibus, rhoncus neque at, vulputate tellus. Aenean accumsan ante velit, sed tincidunt tortor sagittis vel.'),
  ('A meaty article', 'Bacon ipsum dolor amet frankfurter salami flank andouille bresaola, hamburger biltong. Pig kevin drumstick landjaeger. Leberkas pastrami filet mignon tenderloin cow. Ham ball tip drumstick andouille boudin landjaeger swine cow. Biltong rump beef ribs pork chop landjaeger. Pork frankfurter leberkas jowl pancetta shankle shank chuck meatball cow sirloin tail flank capicola.<br><br>Turkey alcatra venison landjaeger ham hock doner ball tip capicola swine bacon picanha burgdoggen. Sausage hamburger shank pig tongue turducken. Landjaeger cow prosciutto porchetta fatback shoulder corned beef beef ribs doner meatball rump bresaola venison beef. Fatback andouille pork chop picanha, doner cupim meatball burgdoggen jowl bresaola. Shankle jerky pork loin picanha sirloin bresaola meatloaf, pork belly pastrami doner. Pork loin pork belly biltong filet mignon short ribs chuck pastrami pig t-bone pork chop frankfurter.'),
  ('An article title', 'Kevin capicola cupim pastrami tenderloin picanha pork belly strip steak turducken chuck pig pancetta bresaola. Kielbasa shank pork loin drumstick turkey capicola fatback. Ham hock short loin kielbasa biltong, boudin pork chop chicken salami beef doner prosciutto ground round alcatra. Pork chop beef swine turkey alcatra ribeye short ribs doner jerky pancetta. Tail salami tongue, bresaola kevin venison ball tip corned beef spare ribs burgdoggen alcatra pastrami.<br><br>Rump ribeye doner leberkas jerky. Spare ribs drumstick corned beef filet mignon chuck boudin, ham hock beef. Meatball salami shankle porchetta cow drumstick pork loin venison doner flank tenderloin sausage ground round short ribs. Landjaeger tongue cow, shankle picanha salami jerky sausage shoulder andouille doner jowl swine pastrami sirloin. Strip steak boudin picanha meatball jerky ground round landjaeger sirloin chuck t-bone sausage kevin pork biltong porchetta. Swine venison prosciutto landjaeger chuck short ribs kielbasa.'),
  ('Neque porro quisquam est qui', 'Bacon shankle flank, landjaeger capicola burgdoggen shank cow venison biltong rump ground round ham. Shankle jerky sirloin porchetta, cupim short loin bresaola pork chop jowl tri-tip chuck capicola. Meatloaf shankle sausage spare ribs frankfurter jerky. Bresaola jerky burgdoggen, filet mignon leberkas corned beef ham. Turducken cow meatball venison tail doner bacon turkey landjaeger biltong chicken. Beef ribs pork belly tail rump. Hamburger alcatra biltong, ground round pastrami chicken turducken.'),
  ('Some lorem ipsum information', 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.<br><br>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.');